apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: tsetjfrog0211a-gitops
  description: This is GitOps manifest for tsetjfrog0211a   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: tsetjfrog0211a
    backstage.io/kubernetes-id: tsetjfrog0211a 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: tsetjfrog0211a   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:tsetjfrog0211a
