apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: tsetjfrog0211a
  janus-idp.io/tekton: tsetjfrog0211a
  backstage.io/kubernetes-id: tsetjfrog0211a
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: tsetjfrog0211a
resources:
- deployment.yaml
- route.yaml
- service.yaml
