apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: tsetjfrog0211a
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: tsetjfrog0211a 
  name: tsetjfrog0211a
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: tsetjfrog0211a 
